% Auto-generated by cameraCalibrator app on 24-Aug-2015
%-------------------------------------------------------


% Define images to process
imageFileNames = {'/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824140907.868_55ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824140933.965_55ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824140937.949_58ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824140943.073_58ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141002.645_58ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141047.183_29ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141108.933_29ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141136.827_25ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141200.887_76ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141204.856_71ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141220.075_71ms.3d.png',...
    '/Users/hannah/Documents/Hanlon Lab/Flounder Project/Data/Calibration/20150824141247.084_69ms.3d.png',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 23;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm');

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('SparseReconstructionExample')
